theme: jekyll-theme-cayman
title: Linux Siglent SDM 3055 Digital Multimeter Control Python VXI / LXI
description: Linux / Debian / RaspiOS, Siglent SDM3055, SDM3055-SC
google_analytics: UA-48643838-1
